{
 "title": "Workspace-1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Business Initiate",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with cte1 as (\r\n    select * from \"Contact\"\r\n    where \"workspaceId\" = 'template-workspace-name'\r\n    and channel = 'whatsapp'\r\n),\r\ncte2 as (select *,\r\n     row_number() over (partition by \"workspaceId\" order by \"createdAt\" desc) as rn\r\nfrom \"Message\" where \"senderType\" = 'user' and \"workspaceId\" = 'template-workspace-name'),\r\ncte3 as (select * from cte2 where rn = 1),\r\ncte4 as (select\r\n       c1.\"phoneNumber\",\r\n       status,\r\n       pricing\r\nfrom \"WhatsappConversation\" wc\r\nleft join cte1 c1 on wc.\"waRecipient\" = c1.\"phoneNumber\"\r\nleft join cte3 c3 on c1.id = c3.\"senderId\"\r\nwhere wc.\"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name')),\r\n    result as (\r\nselect \"broadcastName\", name, \"phoneNumber\", BD.\"createdAt\", \"templateName\", c4.status, pricing from \"Broadcast\" left join \"BroadcastData\" BD on \"Broadcast\".id = BD.\"broadcastId\"\r\nleft join cte1 c1 using (\"phoneNumber\")\r\nleft join cte4 c4 using (\"phoneNumber\")\r\nwhere \"Broadcast\".\"workspaceId\" = 'template-workspace-name')\r\nselect \"broadcastName\" as \"Broadcast Name\", name as \"Whatsapp Account\", \"phoneNumber\" as \"Recipients Number\", \"createdAt\" as time, \"templateName\" as \"Message Template\", status as \"Message Last Status\", pricing as \"Source\" from result group by 1,2,3,4,5,6,7"
    }
   ]
  },
  {
   "title": "All Conversation",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "with cte1 as (\r\n    select * from \"Contact\"\r\n    where \"workspaceId\" = 'template-workspace-name'\r\n    and channel = 'whatsapp'\r\n),\r\ncte2 as (select *,\r\n         row_number() over (partition by \"workspaceId\" order by \"createdAt\" desc) as rn\r\n  from \"Message\" where \"senderType\" = 'user' and \"workspaceId\" = 'template-workspace-name'),\r\ncte3 as (select * from cte2 where rn = 1)\r\nselect wc.\"createdAt\" as time,\r\n       name as \"Whatsapp Account\",\r\n       wc.\"waRecipient\" as \"Recipient Number\",\r\n       \"waOriginType\" as \"Type\",\r\n       status as \"Message Last Status\",\r\n       pricing as \"Source\"\r\nfrom \"WhatsappConversation\" wc\r\nleft join cte1 c1 on wc.\"waRecipient\" = c1.\"phoneNumber\"\r\nleft join cte3 c3 on c1.id = c3.\"senderId\"\r\nwhere wc.\"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name'\r\norder by 1 desc)"
    }
   ]
  },
  { "title": "Billing information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Billing information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "rawSql": "select count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 +\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 +\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 +\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as total_bill,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 as bill_service,\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 as bill_marketing,\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 as bill_utility,\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as bill_authentication\r\nfrom \"WhatsappConversation\"\r\nwhere \"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name')\r\n"
    }
   ]
  },
  {
   "title": "Billing information over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', \"createdAt\") as time,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 +\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 +\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 +\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as total_bill,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 as bill_service,\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 as bill_marketing,\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 as bill_utility,\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as bill_authentication\r\nfrom \"WhatsappConversation\"\r\nwhere \"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name')\r\ngroup by 1\r\n"
    }
   ]
  },
  { "title": "Workspace Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Flow Information",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)                                                                                 as \"Number of Broadcast\",\r\n       (select count(*) from \"Conversation\" where \"Conversation\".\"workspaceId\" = 'template-workspace-name') as \"Number of Conversation Open\",\r\n       (with cte1 as (select \"conversationId\", status, \"senderType\",\r\n         row_number() over (partition by \"conversationId\" order by \"createdAt\" desc) as rn\r\n  from \"Message\" where \"senderType\" = 'user' and \"workspaceId\" = 'template-workspace-name')\r\nselect count(*) from cte1 where rn = 1) as \"Number of User Reply Broadcast\"\r\n                                                                                                   from \"Broadcast\"\r\nwhere \"workspaceId\" = 'template-workspace-name'"
    }
   ]
  },
  {
   "title": "Number of Broadcast over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', \"createdAt\"), count(*) as \"Total\" from \"Broadcast\" where \"workspaceId\" = 'template-workspace-name' group by 1"
    }
   ]
  },
  {
   "title": "Number of Message over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', \"createdAt\") as time, count(*) as \"Total\", count(*) filter(where \"senderType\" = 'user') as in, count(*) filter(where \"senderType\" != 'user' ) as out from \"Message\" where \"workspaceId\" = 'template-workspace-name' group by 1"
    }
   ]
  }
 ]
}