{
 "title": "template-workspace-name",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Conversations Count",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select count(*) filter ( where \"waOriginType\" = 'user_initiated') as user_initiated,\r\n       count(*) filter ( where \"waOriginType\" = 'service') as service,\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' )                   as marketing,\r\n       count(*) filter ( where \"waOriginType\" = 'utility')                      as utility,\r\n       count(*) filter ( where \"waOriginType\" = 'authentication')               as authentication,\r\n       count(*) as \"total_converstation\",\r\n       (select count(distinct id)\r\n        from \"Broadcast\"\r\n        where \"workspaceId\" = 'template-workspace-name'\r\n          and $__timeFilter(\"Broadcast\".\"createdAt\"))    as total_broadcast\r\nfrom \"WhatsappConversation\"\r\nwhere \"channelId\" in (select \"channelId\"\r\n                      from \"Broadcast\"\r\n                      where \"workspaceId\" = 'template-workspace-name'\r\n                        and $__timeFilter(\"Broadcast\".\"createdAt\"))\r\nand pricing = 'Paid'\r\nand $__timeFilter(\"createdAt\");"
    }
   ]
  },
  {
   "title": "All Conversation",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "with cte1 as (\r\n    select * from \"Contact\"\r\n    where \"workspaceId\" = 'template-workspace-name'\r\n    and channel = 'whatsapp'\r\n),\r\ncte2 as (select *,\r\n         row_number() over (partition by \"workspaceId\" order by \"createdAt\" desc) as rn\r\n  from \"Message\" where \"senderType\" = 'user' and \"workspaceId\" = 'template-workspace-name'),\r\ncte3 as (select * from cte2 where rn = 1)\r\nselect wc.\"createdAt\" as time,\r\n       name as \"Whatsapp Account\",\r\n       wc.\"waRecipient\" as \"Recipient Number\",\r\n       \"waOriginType\" as \"Type\",\r\n       status as \"Message Last Status\",\r\n       pricing as \"Source\"\r\nfrom \"WhatsappConversation\" wc\r\nleft join cte1 c1 on wc.\"waRecipient\" = c1.\"phoneNumber\"\r\nleft join cte3 c3 on c1.id = c3.\"senderId\"\r\nwhere wc.\"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name'\r\norder by 1 desc) and $__timeFilter(wc.\"createdAt\")\r\norder by 1 desc"
    }
   ]
  },
  { "title": "Billing information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Billing information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "rawSql": "select \r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 306 as bill_service,\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 657 as bill_marketing,\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 321 as bill_utility,\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 460 as bill_authentication,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 306 +\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 657 +\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 321 +\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 460 as total_bill\r\nfrom \"WhatsappConversation\"\r\nwhere \"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name') and $__timeFilter(\"createdAt\")\r\n"
    }
   ]
  },
  {
   "title": "Billing information over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', \"createdAt\") as time,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 +\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 +\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 +\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as total_bill,\r\n       count(*) filter ( where \"waOriginType\" in ('user_initiated', 'service')) * 270.48 as bill_service,\r\n       count(*) filter ( where \"waOriginType\" = 'marketing' ) * 586.33 as bill_marketing,\r\n       count(*) filter ( where \"waOriginType\" = 'utility') * 285.32 as bill_utility,\r\n       count(*) filter ( where \"waOriginType\" = 'authentication') * 427.97 as bill_authentication\r\nfrom \"WhatsappConversation\"\r\nwhere \"channelId\" in (select \"id\" from \"Channel\" where \"workspaceId\" = 'template-workspace-name')\r\ngroup by 1\r\n"
    }
   ]
  }
 ]
}